import os

MIN_SCREEN_SIZE = (640, 360)
GAME_SIZE = (1280, 720)
CAPTION = "Checking it twice!"

FPS = 60
WORLD_SPEED = 100
GRAVITY = WORLD_SPEED * 3

SCORE_TEXT_COLOR = (82, 48, 22)

PROMPT_OFFSET_Y = GAME_SIZE[1] * 0.03

DELIVERY_POINTS = 10
FALSE_DELIVERY_POINTS = -5

FILE_PATH = os.path.abspath(__file__)
SRC_DIR = os.path.dirname(FILE_PATH)
BASE_DIR = os.path.dirname(SRC_DIR)
ASSETS_DIR = os.path.join(BASE_DIR, 'assets')

GROUND_LEVEL = GAME_SIZE[1]/1.15
BAR_HEIGHT = GAME_SIZE[1]*0.007
BAR_SIDE_MARGINS = BAR_HEIGHT
BAR_OPACITY = 0

MUSIC_CHANNEL_ID = 7